/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MCSH_index_Nsw_Nsw2 */

#ifndef _Included_MCSH_index_Nsw_Nsw2
#define _Included_MCSH_index_Nsw_Nsw2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MCSH_index_Nsw_Nsw2
 * Method:    search
 * Signature: ([FIIILjava/lang/String;[FIIF)[I
 */
JNIEXPORT jintArray JNICALL Java_MCSH_index_Nsw_Nsw2_search
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint, jstring, jfloatArray, jint, jint, jfloat);

/*
 * Class:     MCSH_index_Nsw_Nsw2
 * Method:    build
 * Signature: (Ljava/lang/String;Ljava/lang/String;[FIIIIF)V
 */
JNIEXPORT void JNICALL Java_MCSH_index_Nsw_Nsw2_build
  (JNIEnv *, jobject, jstring, jstring, jfloatArray, jint, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
