/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MCSH_index_Nsw_Nsw */

#ifndef _Included_MCSH_index_Nsw_Nsw
#define _Included_MCSH_index_Nsw_Nsw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MCSH_index_Nsw_Nsw
 * Method:    search
 * Signature: ([FIIILjava/lang/String;[FII)[I
 */
JNIEXPORT jintArray JNICALL Java_MCSH_index_Nsw_Nsw_search
  (JNIEnv *, jobject, jfloatArray, jint, jint, jint, jstring, jfloatArray, jint, jint);

/*
 * Class:     MCSH_index_Nsw_Nsw
 * Method:    build
 * Signature: (Ljava/lang/String;Ljava/lang/String;[FIIII)V
 */
JNIEXPORT void JNICALL Java_MCSH_index_Nsw_Nsw_build
  (JNIEnv *, jobject, jstring, jstring, jfloatArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
